apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  postgres-password: postgres
  rabbitmq-username: app_user
  rabbitmq-password: app_password
  rabbitmq-erlang-cookie: microservices-dev-cookie
  database-url-core: postgresql+psycopg://postgres:postgres@postgres-core:5432/polling
  database-url-users: postgresql+psycopg://postgres:postgres@postgres-users:5432/users
  database-url-notification: postgresql+psycopg://postgres:postgres@postgres-notification:5432/notifications
  database-url-workflow: postgresql+asyncpg://postgres:postgres@postgres-workflow:5432/workflows
