from typing import Protocol
from uuid import UUID

from src.core_service.app.core.domain import Poll


class PollRepositoryProtocol(Protocol):
    def find_by_id(self, poll_id: UUID, user_id: UUID) -> Poll | None: ...

    def find_by_id_any_user(self, poll_id: UUID) -> Poll | None: ...

    def save(self, poll: Poll) -> Poll: ...

    def delete(self, poll_id: UUID, user_id: UUID) -> None: ...

    def exists_by_id(self, poll_id: UUID) -> bool: ...
